package com.training.gradleplugins.core;// default package
// Generated 10/04/2014 12:23:33 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * CategoryType generated by hbm2java
 */
@Entity
@Table(name = "category_type", catalog = "winbits", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class CategoryType implements java.io.Serializable {

	private Long id;
	private long version;
	private String description;
	private String name;
	private Set<ItemGroup> itemGroups = new HashSet<ItemGroup>(0);

	public CategoryType() {
	}

	public CategoryType(String name) {
		this.name = name;
	}

	public CategoryType(String description, String name,
			Set<ItemGroup> itemGroups) {
		this.description = description;
		this.name = name;
		this.itemGroups = itemGroups;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@Column(name = "description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "name", unique = true, nullable = false, length = 25)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoryType")
	public Set<ItemGroup> getItemGroups() {
		return this.itemGroups;
	}

	public void setItemGroups(Set<ItemGroup> itemGroups) {
		this.itemGroups = itemGroups;
	}

}
